project:
  type: website
  title: "CSU COAST Summer Internship 2024"

website:
  title: "CSU COAST Summer Internship 2024"
  sidebar:
    background: "#D9E3E8"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Milestones"
        contents:
          - href: milestones/milestone1.qmd
            text: "Milestone 1"
          - href: milestones/milestone2.qmd
            text: "Milestone 2"
          - href: milestones/milestone3.qmd
            text: "Milestone 3"
          - href: milestones/milestone4.qmd
            text: "Milestone 4"
      - href: resources.qmd
        text: "Resources"
      - href: about.qmd
        text: "About Me"
  page-navigation: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple